name: Publish Demo to GitHub Pages

on:
  push:
    branches: 
      - demo

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      
      - name: Install Dependencies
        run: npm ci
        
      - name: Predeploy
        run: npm run build     

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
