name: Publish Demo to GitHub Pages

on:
  push:
    branches: 
      - demo

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      
      - name: Install Dependencies
        run: npm ci
        
      - name: Predeploy
        run: npm run build     

      - name: Deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "revocalendar+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "🚀 update demo site"
          git push origin gh-pages
